version: 2.1

jobs:
  linux-build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake ninja clang llvm
      - run: mkdir build && cd build
      - run: CC=clang CXX=clang++ LDFLAGS=-fuse-ld=lld cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
      - run: cmake --build .
      - persist_to_workspace

  linux-tests:
    docker:
      - image: cimg/base:current

    steps:
      - attach_workspace
      - run: cd build
      - run: ctest .

workflows:
  linux-testing:
    jobs:
      - linux-build
      - linux-tests:
          requires:
            - linux-build